#Requires -Version 5.1
<#
.SYNOPSIS
  Mirror .agent-workflow rules and skills into .cursor/ for Cursor IDE.

.DESCRIPTION
  Cursor reads project rules from .cursor/rules and skills from .cursor/skills.
  The canonical kit lives in .agent-workflow/ (gitignored). Re-run after Apply -Force
  or when you update rules in the template.

.PARAMETER TargetRepo
  Absolute path to the repository root.
#>
param(
  [Parameter(Mandatory = $true)]
  [string] $TargetRepo
)

$ErrorActionPreference = "Stop"
$Kit = Join-Path $TargetRepo ".agent-workflow"
if (-not (Test-Path $Kit)) {
  throw "Missing $Kit - run Apply-AgentWorkflow.ps1 first."
}

$CursorRoot = Join-Path $TargetRepo ".cursor"
$Pairs = @(
  @{ From = "rules"; To = "rules" },
  @{ From = "skills"; To = "skills" }
)

foreach ($p in $Pairs) {
  $src = Join-Path $Kit $p.From
  $dst = Join-Path $CursorRoot $p.To
  if (-not (Test-Path $src)) { continue }
  if (-not (Test-Path $dst)) {
    New-Item -ItemType Directory -Force -Path $dst | Out-Null
  }
  Get-ChildItem -LiteralPath $src -Recurse -File | ForEach-Object {
    $rel = $_.FullName.Substring($src.Length).TrimStart('\', '/')
    $out = Join-Path $dst $rel
    $outDir = Split-Path $out -Parent
    if (-not (Test-Path $outDir)) {
      New-Item -ItemType Directory -Force -Path $outDir | Out-Null
    }
    Copy-Item -LiteralPath $_.FullName -Destination $out -Force
  }
  Write-Host "Synced $($p.From) -> .cursor/$($p.To)"
}

$note = @"
# Generated by agent-workflow-template — do not edit by hand.
# Canonical source: .agent-workflow/
# Re-run: scripts/adapters/Sync-CursorRules.ps1 (from template repo) or your wrapper.
"@
Set-Content -Path (Join-Path $CursorRoot "README.sync.md") -Value $note -Encoding utf8
Write-Host "Cursor adapter done. Open the repo in Cursor; rules should load from .cursor/rules."
